/* Fleet Appearance Audit — service worker v0.5.2 (generated by build.js; lives next to audit.html on the host).
   Versioned app-shell cache: instant, offline launch from the home screen. A new build ships a new sw.js (new
   version string), which installs its own cache and waits; the running app offers "Reload", posts skipWaiting,
   and the new worker takes over and drops the old cache. Nothing here touches audit data (IndexedDB). */
var VERSION='0.5.2';var CACHE='fleet-audit-'+VERSION;
var REQUIRED=['./audit.html'];var OPTIONAL=['./index.html','./manifest.webmanifest','./apple-touch-icon.png','./icon-192.png','./icon-512.png'];
function fetchFresh(u){return fetch(u,{cache:'reload'});}
self.addEventListener('install',function(e){e.waitUntil(caches.open(CACHE).then(function(c){
  return Promise.all(REQUIRED.map(function(u){return fetchFresh(u).then(function(r){if(!r.ok)throw new Error(u+' '+r.status);return c.put(u,r);});}))
    .then(function(){return Promise.all(OPTIONAL.map(function(u){return fetchFresh(u).then(function(r){if(r.ok)return c.put(u,r);}).catch(function(){});}));});
}));});
self.addEventListener('activate',function(e){e.waitUntil(caches.keys().then(function(keys){
  return Promise.all(keys.filter(function(k){return k.indexOf('fleet-audit-')===0&&k!==CACHE;}).map(function(k){return caches.delete(k);}));
}).then(function(){return self.clients.claim();}));});
self.addEventListener('message',function(e){if(e.data&&e.data.type==='skipWaiting')self.skipWaiting();});
self.addEventListener('fetch',function(e){var req=e.request;if(req.method!=='GET')return;var url;try{url=new URL(req.url);}catch(err){return;}if(url.origin!==self.location.origin)return;
  e.respondWith(caches.open(CACHE).then(function(c){
    var path=url.pathname;var welcome=/\/$/.test(path)||/\/index\.html$/.test(path);var key=welcome?'./index.html':null;
    // The welcome page is network-first so QR/copy changes appear without getting trapped behind an older shell cache.
    if(welcome)return fetch(req,{cache:'reload'}).then(function(r){if(r&&r.ok)c.put('./index.html',r.clone());return r;}).catch(function(){return c.match('./index.html').then(function(h){return h||new Response('Offline and no saved copy yet. Open the link once with signal.',{status:503,headers:{'Content-Type':'text/plain'}});});});
    return c.match(req,{ignoreSearch:true}).then(function(hit){if(hit)return hit;
      return fetch(req).then(function(r){return r;}).catch(function(){
        if(req.mode==='navigate')return c.match('./audit.html').then(function(h){return h||new Response('Offline and no saved copy yet. Open the link once with signal.',{status:503,headers:{'Content-Type':'text/plain'}});});
        return new Response('',{status:504});
      });
    });
  }));
});
