/* Fleet Appearance Audit — service worker v0.5.5 (generated by build.js; lives next to audit.html on the host).
   Versioned app-shell cache: instant, offline launch from the home screen. A new build ships a new sw.js (new
   version string), which installs its own cache and waits; the running app offers "Reload", posts skipWaiting,
   and the new worker takes over and drops the old cache. Nothing here touches audit data (IndexedDB).
   Fetch policy (0.5.3): audit.html is cache-first and changes only when a new sw.js installs, so the app and its
   worker always move together. Everything else in the shell (welcome page, manifest, icons) is network-first with
   the cached copy as the offline / slow-signal fallback, so an edit on the host shows on the next online visit. */
var VERSION='0.5.5';var CACHE='fleet-audit-'+VERSION;
var REQUIRED=['./audit.html'];var OPTIONAL=['./index.html','./manifest.webmanifest','./apple-touch-icon.png','./icon-192.png','./icon-512.png'];
var NET_WAIT_MS=3000;
function fetchFresh(u){return fetch(u,{cache:'reload'});}
self.addEventListener('install',function(e){e.waitUntil(caches.open(CACHE).then(function(c){
  return Promise.all(REQUIRED.map(function(u){return fetchFresh(u).then(function(r){if(!r.ok)throw new Error(u+' '+r.status);return c.put(u,r);});}))
    .then(function(){return Promise.all(OPTIONAL.map(function(u){return fetchFresh(u).then(function(r){if(r.ok)return c.put(u,r);}).catch(function(){});}));});
}));});
self.addEventListener('activate',function(e){e.waitUntil(caches.keys().then(function(keys){
  return Promise.all(keys.filter(function(k){return k.indexOf('fleet-audit-')===0&&k!==CACHE;}).map(function(k){return caches.delete(k);}));
}).then(function(){return self.clients.claim();}));});
self.addEventListener('message',function(e){if(e.data&&e.data.type==='skipWaiting')self.skipWaiting();});
function offlineNote(){return new Response('Offline and no saved copy yet. Open the link once with signal.',{status:503,headers:{'Content-Type':'text/plain'}});}
self.addEventListener('fetch',function(e){var req=e.request;if(req.method!=='GET')return;var url;try{url=new URL(req.url);}catch(err){return;}if(url.origin!==self.location.origin)return;
  var path=url.pathname,nav=req.mode==='navigate';
  var base=new URL('./',self.location.href).pathname;var rel='./'+(path.indexOf(base)===0?path.slice(base.length):path);if(rel==='./')rel='./index.html';
  var cacheP=caches.open(CACHE);
  // the app: cache-first, never refreshed here — only a new sw.js (install above) replaces it
  if(rel==='./audit.html'){e.respondWith(cacheP.then(function(c){return c.match('./audit.html');}).then(function(hit){return hit||fetch(req).catch(offlineNote);}));return;}
  var shell=OPTIONAL.indexOf(rel)>=0;
  function saved(){return cacheP.then(function(c){return c.match(rel).then(function(hit){if(hit)return hit;if(nav)return c.match('./audit.html').then(function(h){return h||offlineNote();});return new Response('',{status:504});});});}
  // everything else: network first (revalidated past the HTTP cache); a good answer refreshes the offline copy
  var net=fetch(req,{cache:'no-cache'}).then(function(r){if(!(shell&&r&&r.ok&&r.type==='basic'))return r;var copy=r.clone();return cacheP.then(function(c){return c.put(rel,copy);}).then(function(){return r;},function(){return r;});});
  if(!shell){e.respondWith(net.catch(saved));return;}
  e.waitUntil(net.catch(function(){}));
  // slow signal: after NET_WAIT_MS serve the saved copy; the fetch keeps going (waitUntil above) and refreshes it for next time
  e.respondWith(new Promise(function(res){var done=false;function finish(v){if(!done){done=true;res(v);}}
    var timer=setTimeout(function(){cacheP.then(function(c){return c.match(rel);}).then(function(hit){if(hit)finish(hit);});},NET_WAIT_MS);
    net.then(function(r){clearTimeout(timer);finish(r);},function(){clearTimeout(timer);saved().then(finish);});
  }));
});
